
version: 2

models:
  - name: dim_seller
    description: "A seller dbt model"
    columns:
      - name: seller_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null


