
version: 2

models:
  - name: fact_order
    description: "A order dbt model"
    columns:
      - name: customer_id
        description: "The customer order for this table"
        data_tests:
          - not_null
  - name: fact_order_items
    description: "A order items dbt model"
    columns:
      - name: order_item_id
        description: "Order items for this table"
        data_tests:
          - not_null



